/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniexample_juav_NativeHelloworld */

#ifndef _Included_jniexample_juav_NativeHelloworld
#define _Included_jniexample_juav_NativeHelloworld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniexample_juav_NativeHelloworld
 * Method:    nativePrint1
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jniexample_juav_NativeHelloworld_nativePrint1
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jniexample_juav_NativeHelloworld
 * Method:    nativePrint2
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jniexample_juav_NativeHelloworld_nativePrint2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
