/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_jni_tasks_NativeTasks */

#ifndef _Included_ub_cse_juav_jni_tasks_NativeTasks
#define _Included_ub_cse_juav_jni_tasks_NativeTasks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    atmosphereUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_atmosphereUpdate
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    autoPilotRunSystimeStep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_autoPilotRunSystimeStep
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    fdmRunStep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_fdmRunStep
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    sensorsRunStep
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_sensorsRunStep
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    autoPilotRunStep
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_autoPilotRunStep
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsAutopilotRunStepRadio
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsAutopilotRunStepRadio
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsAutopilotRunStepOverwriteIns
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsAutopilotRunStepOverwriteIns
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsAutopilotRunStepOverwriteAhrs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsAutopilotRunStepOverwriteAhrs
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsAutopilotRunStepHandelPeriodicTasks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsAutopilotRunStepHandelPeriodicTasks
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsAutopilotRunStepConvertMotorMixingCommandsToAutopilotCommands
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsAutopilotRunStepConvertMotorMixingCommandsToAutopilotCommands
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsElectricalRunStep
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsElectricalRunStep
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    sendBarometricReading
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_sendBarometricReading
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorInitGyro
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorInitGyro
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorInitAccel
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorInitAccel
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorInitMag
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorInitMag
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorInitBaro
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorInitBaro
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorInitGps
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorInitGps
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFdmCopyGyro
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFdmCopyGyro
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFdmCopyAccel
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFdmCopyAccel
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFdmCopyMag
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFdmCopyMag
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFdmCopyBaro
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFdmCopyBaro
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFdmCopyGps
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFdmCopyGps
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFeedStepGyro
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFeedStepGyro
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFeedStepAccel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFeedStepAccel
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFeedStepMag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFeedStepMag
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFeedStepBaro
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFeedStepBaro
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFeedStepGps
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFeedStepGps
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    mainPeriodicJuavAutopilotPrior
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_mainPeriodicJuavAutopilotPrior
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    sysTimeCheckAndAckTimerMainPeriodicJuav
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_sysTimeCheckAndAckTimerMainPeriodicJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    handlePeriodicTasksFollowingMainPeriodicJuav
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_handlePeriodicTasksFollowingMainPeriodicJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    autopilotPeriodicPriorJuav
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_autopilotPeriodicPriorJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    isAutopilotModeApModeKillJuav
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_isAutopilotModeApModeKillJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    autopilotPeriodicPostJuav
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_autopilotPeriodicPostJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    guidanceHRunJuav
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_guidanceHRunJuav
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAutopilotInFlightJuav
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAutopilotInFlightJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    runStabilizationAttitudeRunJuav
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_runStabilizationAttitudeRunJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    guidanceHRunNativeTestJuav
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_guidanceHRunNativeTestJuav
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    mainPeriodicJuavAutopilotPost
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_mainPeriodicJuavAutopilotPost
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    mainPeriodicJuavTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_mainPeriodicJuavTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
