/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_jni_tasks_NativeTasks */

#ifndef _Included_ub_cse_juav_jni_tasks_NativeTasks
#define _Included_ub_cse_juav_jni_tasks_NativeTasks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    atmosphereUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_atmosphereUpdate
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    autoPilotRunSystimeStep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_autoPilotRunSystimeStep
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    fdmRunStep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_fdmRunStep
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    sensorsRunStep
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_sensorsRunStep
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    autoPilotRunStep
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_autoPilotRunStep
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsAutopilotRunStepRadio
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsAutopilotRunStepRadio
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsAutopilotRunStepOverwriteIns
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsAutopilotRunStepOverwriteIns
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsAutopilotRunStepOverwriteAhrs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsAutopilotRunStepOverwriteAhrs
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsAutopilotRunStepHandelPeriodicTasks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsAutopilotRunStepHandelPeriodicTasks
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsAutopilotRunStepConvertMotorMixingCommandsToAutopilotCommands
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsAutopilotRunStepConvertMotorMixingCommandsToAutopilotCommands
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsElectricalRunStep
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsElectricalRunStep
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    sendBarometricReading
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_sendBarometricReading
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorInitGyro
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorInitGyro
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorInitAccel
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorInitAccel
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorInitMag
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorInitMag
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorInitBaro
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorInitBaro
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorInitGps
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorInitGps
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFdmCopyGyro
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFdmCopyGyro
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFdmCopyAccel
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFdmCopyAccel
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFdmCopyMag
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFdmCopyMag
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFdmCopyBaro
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFdmCopyBaro
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFdmCopyGps
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFdmCopyGps
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFeedStepGyro
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFeedStepGyro
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFeedStepAccel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFeedStepAccel
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFeedStepMag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFeedStepMag
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFeedStepBaro
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFeedStepBaro
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    npsSensorFeedStepGps
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_npsSensorFeedStepGps
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    mainPeriodicJuavAutopilotPrior
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_mainPeriodicJuavAutopilotPrior
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    sysTimeCheckAndAckTimerMainPeriodicJuav
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_sysTimeCheckAndAckTimerMainPeriodicJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    handlePeriodicTasksFollowingMainPeriodicJuav
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_handlePeriodicTasksFollowingMainPeriodicJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    autopilotPeriodicPriorJuav
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_autopilotPeriodicPriorJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    isAutopilotModeApModeKillJuav
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_isAutopilotModeApModeKillJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    autopilotPeriodicPostJuav
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_autopilotPeriodicPostJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    guidanceHRunJuav
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_guidanceHRunJuav
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAutopilotInFlightJuav
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAutopilotInFlightJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    runStabilizationAttitudeRunJuav
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_runStabilizationAttitudeRunJuav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    guidanceHRunNativeTestJuav
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_guidanceHRunNativeTestJuav
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    mainPeriodicJuavAutopilotPost
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_mainPeriodicJuavAutopilotPost
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    mainPeriodicJuavTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_mainPeriodicJuavTest
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    stateGetNedToBodyQuatIQi
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_stateGetNedToBodyQuatIQi
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    stateGetNedToBodyQuatIQx
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_stateGetNedToBodyQuatIQx
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    stateGetNedToBodyQuatIQy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_stateGetNedToBodyQuatIQy
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    stateGetNedToBodyQuatIQz
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_stateGetNedToBodyQuatIQz
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    stateGetBodyRatesIP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_stateGetBodyRatesIP
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    stateGetBodyRatesIQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_stateGetBodyRatesIQ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    stateGetBodyRatesIR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_stateGetBodyRatesIR
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    attitudeRefQuatIntUpdateJuav
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_attitudeRefQuatIntUpdateJuav
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getStabilizationAttSumErrQuatQi
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getStabilizationAttSumErrQuatQi
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getStabilizationAttSumErrQuatQx
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getStabilizationAttSumErrQuatQx
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getStabilizationAttSumErrQuatQy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getStabilizationAttSumErrQuatQy
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getStabilizationAttSumErrQuatQz
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getStabilizationAttSumErrQuatQz
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeRefQuatQi
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeRefQuatQi
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeRefQuatQx
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeRefQuatQx
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeRefQuatQy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeRefQuatQy
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeRefQuatQz
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeRefQuatQz
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeRefRateP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeRefRateP
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeRefRateQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeRefRateQ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeRefRateR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeRefRateR
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainPX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainPX
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainPY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainPY
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainPZ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainPZ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainDX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainDX
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainDY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainDY
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainDZ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainDZ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainDdX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainDdX
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainDdY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainDdY
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainDdZ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainDdZ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainIX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainIX
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainIY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainIY
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeGainIZ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeGainIZ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeRefAccelP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeRefAccelP
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeRefAccelQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeRefAccelQ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    getAttitudeRefAccelR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_getAttitudeRefAccelR
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setStabilizationAttSumErrQuatQi
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setStabilizationAttSumErrQuatQi
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setStabilizationAttSumErrQuatQx
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setStabilizationAttSumErrQuatQx
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setStabilizationAttSumErrQuatQy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setStabilizationAttSumErrQuatQy
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setStabilizationAttSumErrQuatQz
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setStabilizationAttSumErrQuatQz
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setAttRefQuatIQuatQi
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setAttRefQuatIQuatQi
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setAttRefQuatIQuatQx
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setAttRefQuatIQuatQx
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setAttRefQuatIQuatQy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setAttRefQuatIQuatQy
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setAttRefQuatIQuatQz
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setAttRefQuatIQuatQz
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setAttRefQuatIRateP
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setAttRefQuatIRateP
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setAttRefQuatIRateQ
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setAttRefQuatIRateQ
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setAttRefQuatIRateR
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setAttRefQuatIRateR
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setAttRefQuatIAccelP
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setAttRefQuatIAccelP
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setAttRefQuatIAccelQ
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setAttRefQuatIAccelQ
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setAttRefQuatIAccelR
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setAttRefQuatIAccelR
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_tasks_NativeTasks
 * Method:    setStabilizationCommands
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_tasks_NativeTasks_setStabilizationCommands
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
