/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_jni_nps_PaparazziNps */

#ifndef _Included_ub_cse_juav_jni_nps_PaparazziNps
#define _Included_ub_cse_juav_jni_nps_PaparazziNps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    npsInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_npsInit
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    npsMainPeriodicJuavNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_npsMainPeriodicJuavNative
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    npsMainDisplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_npsMainDisplay
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    setNpsMainSimTime
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_setNpsMainSimTime
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    getNpsMainSimTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_getNpsMainSimTime
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    getNpsMainHostTimeElapsed
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_getNpsMainHostTimeElapsed
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    getNpsMainSimDt
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_getNpsMainSimDt
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    getNpsMainRealInitialTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_getNpsMainRealInitialTime
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    getHostTimeNow
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_getHostTimeNow
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    getNpsMainDisplayTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_getNpsMainDisplayTime
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    getNpsMainDisplayDt
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_getNpsMainDisplayDt
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    setNpsMainDisplayTime
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_setNpsMainDisplayTime
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_nps_PaparazziNps
 * Method:    mainEvent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_nps_PaparazziNps_mainEvent
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
