/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_sensor_polls_SensorPolls */

#ifndef _Included_ub_cse_juav_sensor_polls_SensorPolls
#define _Included_ub_cse_juav_sensor_polls_SensorPolls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_sensor_polls_SensorPolls
 * Method:    pollGyro
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ub_cse_juav_sensor_polls_SensorPolls_pollGyro
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_sensor_polls_SensorPolls
 * Method:    pollAccelerometer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ub_cse_juav_sensor_polls_SensorPolls_pollAccelerometer
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_sensor_polls_SensorPolls
 * Method:    pollMagnetic
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ub_cse_juav_sensor_polls_SensorPolls_pollMagnetic
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_sensor_polls_SensorPolls
 * Method:    pollBarometer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ub_cse_juav_sensor_polls_SensorPolls_pollBarometer
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_sensor_polls_SensorPolls
 * Method:    pollGps
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ub_cse_juav_sensor_polls_SensorPolls_pollGps
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_sensor_polls_SensorPolls
 * Method:    pollSonar
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ub_cse_juav_sensor_polls_SensorPolls_pollSonar
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
