/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_jni_imu_ImuNative */

#ifndef _Included_ub_cse_juav_jni_imu_ImuNative
#define _Included_ub_cse_juav_jni_imu_ImuNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_jni_imu_ImuNative
 * Method:    imuFeedGyro
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_imu_ImuNative_imuFeedGyro
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     ub_cse_juav_jni_imu_ImuNative
 * Method:    imuFeedAccel
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_imu_ImuNative_imuFeedAccel
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     ub_cse_juav_jni_imu_ImuNative
 * Method:    imuFeedMag
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_imu_ImuNative_imuFeedMag
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
