/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_jni_gps_GpsNative */

#ifndef _Included_ub_cse_juav_jni_gps_GpsNative
#define _Included_ub_cse_juav_jni_gps_GpsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_value_week_juav
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1value_1week_1juav
  (JNIEnv *, jclass, jint);

/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_value_tow_juav
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1value_1tow_1juav
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_value_ecef_pos_juav
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1value_1ecef_1pos_1juav
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_value_ecef_vel_juav
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1value_1ecef_1vel_1juav
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_value_lla_pos_juav
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1value_1lla_1pos_1juav
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_value_hmsl_juav
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1value_1hmsl_1juav
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_value_ned_speed
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1value_1ned_1speed
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_value_finalize_juav
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1value_1finalize_1juav
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_latency_speed_juav
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1latency_1speed_1juav
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_latency_pos_juav
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1latency_1pos_1juav
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_latency_lla_juav
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1latency_1lla_1juav
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ub_cse_juav_jni_gps_GpsNative
 * Method:    gps_feed_latency_hmsl_juav
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_gps_GpsNative_gps_1feed_1latency_1hmsl_1juav
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
