/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_jni_fdm_JniFdm */

#ifndef _Included_ub_cse_juav_jni_fdm_JniFdm
#define _Included_ub_cse_juav_jni_fdm_JniFdm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
