/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_jni_fdm_JniFdm */

#ifndef _Included_ub_cse_juav_jni_fdm_JniFdm
#define _Included_ub_cse_juav_jni_fdm_JniFdm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmBodyInertialRotVelP
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmBodyInertialRotVelP
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmBodyInertialRotVelQ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmBodyInertialRotVelQ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmBodyInertialRotVelR
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmBodyInertialRotVelR
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmBodyAccelX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmBodyAccelX
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmBodyAccelY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmBodyAccelY
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmBodyAccelZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmBodyAccelZ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmBodyToImu
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmBodyToImu
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmLtpToBodyQuatQi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmLtpToBodyQuatQi
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmLtpToBodyQuatQx
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmLtpToBodyQuatQx
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmLtpToBodyQuatQy
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmLtpToBodyQuatQy
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmLtpToBodyQuatQz
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmLtpToBodyQuatQz
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmLtpHX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmLtpHX
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmLtpHY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmLtpHY
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmLtpHZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmLtpHZ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getHmsl
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getHmsl
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmEcefEcefVelX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmEcefEcefVelX
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmEcefEcefVelY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmEcefEcefVelY
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmEcefEcefVelZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmEcefEcefVelZ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmEcefPosX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmEcefPosX
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmEcefPosY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmEcefPosY
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmEcefPosZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmEcefPosZ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_jni_fdm_JniFdm
 * Method:    getFdmAgl
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_jni_fdm_JniFdm_getFdmAgl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
