/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ub_cse_juav_ardupilot_ArdupilotBridge */

#ifndef _Included_ub_cse_juav_ardupilot_ArdupilotBridge
#define _Included_ub_cse_juav_ardupilot_ArdupilotBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    init_base
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_init_1base
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    init_inertial
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_init_1inertial
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    update_inertial
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_update_1inertial
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getFdmBodyAccelX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getFdmBodyAccelX
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getFdmBodyAccelY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getFdmBodyAccelY
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getFdmBodyAccelZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getFdmBodyAccelZ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    init_gps
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_init_1gps
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    updateGps
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_updateGps
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getGpsReadTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getGpsReadTime
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getGpsLatitude
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getGpsLatitude
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getGpsLongitude
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getGpsLongitude
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getGpsAltitude
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getGpsAltitude
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getFdmBodyInertialRotVelP
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getFdmBodyInertialRotVelP
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getFdmBodyInertialRotVelQ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getFdmBodyInertialRotVelQ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getFdmBodyInertialRotVelR
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getFdmBodyInertialRotVelR
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getMagX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getMagX
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getMagY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getMagY
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getMagZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getMagZ
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    init_compass
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_init_1compass
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    updateCompass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_updateCompass
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    initBaro
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_initBaro
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    updateBaro
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_updateBaro
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getBaroPressure
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getBaroPressure
  (JNIEnv *, jclass);

/*
 * Class:     ub_cse_juav_ardupilot_ArdupilotBridge
 * Method:    getBaroAltitude
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ub_cse_juav_ardupilot_ArdupilotBridge_getBaroAltitude
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
